/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class T */
#define  SIZE_MAX 3
#define  BUFSIZE 128
void JstringToChar(JNIEnv *env, jstring mjString, char *buf)
{
	char *c_str;
	c_str = (*env)->GetStringUTFChars(env, mjString, JNI_FALSE);
	sprintf(buf, "%s",c_str);
	//通知本地虚拟机本机代码不再需要通过str访问java字符串
	(*env)->ReleaseStringUTFChars(env, mjString, (const char *)c_str);
	return;
}
/*
 * Class:     T
 * Method:    sendMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_T_sendMessage
	(JNIEnv *env, jobject t, jint rv)
{
	char buf[BUFSIZE]={0};
	rv=sprintf(buf, "Hello, I am from buf array!\n");
	return (*env)->NewStringUTF(env, buf);
}

/*
 * Class:     T
 * Method:    changeMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_T_changeMessage
	(JNIEnv *env, jobject t, jstring mjString, jint rv)
{
	char buf[BUFSIZE]={0};
	char* c_str;
	//从inString字符串取得指向字符串UTF编码的指针
	c_str = (*env)->GetStringUTFChars(env, mjString, JNI_FALSE);
	printf("Hello, I get the '%s' message and will change it!!\n",c_str);
	rv=sprintf(buf, "-----change string is %s over----------",c_str);
	//通知本地虚拟机本机代码不再需要通过str访问java字符串
	(*env)->ReleaseStringUTFChars(env, mjString, (const char *)c_str);
	return (*env)->NewStringUTF(env, buf);
}

/*
 * Class:     T
 * Method:    getMessage
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_T_getMessage
	(JNIEnv *env, jobject t, jint rv)
{
	jstring      str;
	jobjectArray args = 0;
	jsize        len = 5;
	char*        sa[] = { "Hello,", "world!", "JNI", "is", "fun" };
	int          i=0;
	args = (*env)->NewObjectArray(env,len,(*env)->FindClass(env,"java/lang/String"),0);
	for( i=0; i < len; i++ )
	{
		str = (*env)->NewStringUTF(env,sa[i] );
		(*env)->SetObjectArrayElement(env,args, i, str);
	}
	rv=0;
	return args;
}

/*
 * Class:     T
 * Method:    setMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_T_setMessage
	(JNIEnv *env, jobject t, jstring s1, jstring s2, jint rv)
{
	jstring      str;
	jobjectArray args = 0;
	jsize        len = SIZE_MAX;
	int i=0;
	char sbuf[SIZE_MAX][BUFSIZE]={0};
	char rbuf[SIZE_MAX][BUFSIZE]={0};
	/*init*/
	JstringToChar(env, s1, sbuf[0]);
	JstringToChar(env, s2, sbuf[1]);
	JstringToChar(env, s1, sbuf[2]);
	/*do something*/
	for (i=0;i<SIZE_MAX;i++)
	{
		rv=sprintf(rbuf[i],"Hello, %s",sbuf[i]);
	}
	/*do end*/
	args = (*env)->NewObjectArray(env,len,(*env)->FindClass(env,"java/lang/String"),0);
	for( i=0; i < SIZE_MAX; i++ )
	{
		str = (*env)->NewStringUTF(env,rbuf[i] );
		(*env)->SetObjectArrayElement(env,args, i, str);
	}
	return args;
}

/*
 * Class:     T
 * Method:    checkMessage
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_T_checkMessage
	(JNIEnv *env, jobject t, jobjectArray jarray, jint rv)
{
	jstring      str;
	jobjectArray args = 0;
	jsize        len = SIZE_MAX;
	int i=0;
	char sbuf[SIZE_MAX][BUFSIZE]={0};
	char rbuf[SIZE_MAX][BUFSIZE]={0};
	const char* chars;
	//传入的是一个对象数组，要变成char *
	int size=(*env)->GetArrayLength(env, jarray);//得到数组的长度值
	if (size>SIZE_MAX){
		return 0;
	}
	for(i=0;i<size;i++){
			jstring obja=(jstring)(*env)->GetObjectArrayElement(env, jarray, i);
			JstringToChar(env, obja, sbuf[i]);
	}
	/*do something*/
	for (i=0;i<SIZE_MAX;i++)
	{
		rv=sprintf(rbuf[i],"Hello, %s",sbuf[i]);
	}
	/*do end*/
	args = (*env)->NewObjectArray(env, len, (*env)->FindClass(env, "java/lang/String"),0);
	for( i=0; i < SIZE_MAX; i++ )
	{
		str = (*env)->NewStringUTF(env,rbuf[i] );
		(*env)->SetObjectArrayElement(env, args, i, str);
	}
	return args;

}

/*
 * Class:     T
 * Method:    cleanMessage
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_T_cleanMessage
	(JNIEnv *env, jobject t, jobjectArray jarray, jint rv)
{

	int i=0;
	char sbuf[SIZE_MAX][BUFSIZE]={0};
	const char* chars;
	//传入的是一个对象数组，要变成char *
	int size=(*env)->GetArrayLength(env, jarray);//得到数组的长度值
	if (size>SIZE_MAX){
		return;
	}
	for(i=0;i<size;i++){
		jstring obja=(jstring)(*env)->GetObjectArrayElement(env, jarray, i);
		JstringToChar(env, obja, sbuf[i]);
	}
	/*do something*/
	for (i=0;i<SIZE_MAX;i++)
	{
		rv=printf("Hello, %s %d\n",sbuf[i],rv);
	}
	rv=0;
	return;
}
