/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class T */

#ifndef _Included_T
#define _Included_T
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     T
 * Method:    sendMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_T_sendMessage
  (JNIEnv *, jobject, jint);

/*
 * Class:     T
 * Method:    changeMessage
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_T_changeMessage
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     T
 * Method:    getMessage
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_T_getMessage
  (JNIEnv *, jobject, jint);

/*
 * Class:     T
 * Method:    setMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_T_setMessage
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     T
 * Method:    checkMessage
 * Signature: ([Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_T_checkMessage
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     T
 * Method:    cleanMessage
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_T_cleanMessage
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
